### ISSUE TITLE
请问 这个程序 跑多久 便需要刷新 cookies

### ISSUE THREAD

**Issue by harryzjm** [luolongfei/cmcc_signin#1]

**Comment by harryzjm** [comment]
sendkey 只是负责通知吧 可以不加吧

**Comment by luolongfei** [comment]
> sendkey 只是负责通知吧 可以不加吧

是的，可以不加的。目前来看这个cookie好像是永久的，因为每次使用短信方式登录返回的cookie值居然是一样的。不过最好还是加上sendkey，这样如果cookie失效可以第一时间发现。

**Comment by harryzjm** [comment]
@luolongfei  好的 谢谢
